### ISSUE TITLE
What was "new-classic streams" in the readme meant to link to?

### ISSUE THREAD

**Issue by anko** [pull-stream/pull-stream#44]
The Markdown's broken, looks like:

> ![shot](https://cloud.githubusercontent.com/assets/5231746/14413837/09584ac6-ff7e-11e5-81a9-56db896295de.png)

**Comment by yoshuawuyts** [comment]
I reckon it's streams 3 docs; not sure which one they'd be pointing to though

**Comment by dominictarr** [comment]
that is out of date now.

classic streams is stream 1, new streams in streams 2.
using "new" and "classic" is a reference to http://www.coca-colacompany.com/stories/coke-lore-new-coke/

streams2 was ment to be way better than streams1, but added a lot of complexity as well as few improvements.. I always hated it because streams1 was so simple, but streams2 was really too complex to understand well. but ugliest of all, streams2 was backwards compatible with streams1... that was probably where _most_ of the new complexity came from.

That backwards compatibility stuff was always considered just legacy stuff, avoid if you can etc... anyway, they had a better idea and made streams3!

streams3, when you really look at it, is just streams1, but backwards compatible to streams2!

I was somewhat vindicated by this, although it is still way more complex than streams1 ever was, now because of the things needed to make streams2 features work, even though that isn't used when you use the streams normally, only when you trigger streams2 functionality.

**Comment by ahdinosaur** [comment]
closed by #46 ?

**Comment by dominictarr** [comment]
okay I fixed the links (in 3.3.3), closing
