### ISSUE TITLE
standard code style?

### ISSUE THREAD

**Issue by ahdinosaur** [pull-stream/pull-stream#52]
continued from https://github.com/pull-stream/pull-stringify/pull/1#issuecomment-226387130,

i'm keen for us to *recommend* using [`standard`](http://standardjs.com/) for modules within the `pull-stream` org.

why?

- it's a really cheap way to find statically-analyzable bugs, for example i've already found [one bug in `pull-stream`](https://github.com/pull-stream/pull-stream/blob/77bc52bdb99111da104791bc1eb5790ce7874401/throughs.js#L10) thanks to `standard` ([now fixed](https://github.com/pull-stream/pull-stream/blob/master/util/prop.js#L6)).
- it ends any potential bike-shedding over personal style preferences. previously most `pull-stream` modules were written in "Dominic style" (or the style of other module authors), but with the `pull-stream` org i'd prefer we embrace a common style used widely amongst JavaScript community (including the mad science community).
- in general, i want our code to prioritize maintainability over cleverness. after spending lots of time reading through pull stream modules, sometimes it takes a while to understand what's happening, so i'd like to do what i can to make it easier for future contributors. `standard` is _one_ pillar of support here, but obviously not a silver bullet.

**Comment by yoshuawuyts** [comment]
:+1: if we can [focus on style, not punctuation](https://gist.github.com/dominictarr/2401787) + catch bugs more easily that's a good thing imo

**Comment by dominictarr** [comment]
I don't care about standard. I've never used a linter, and I don't feel the need to.
I'm certainly not changing this in one module, unless we change it in every module (over 50)
Doing that is quite a bit of work that I consider pointless, if someone wants other than me wants to write scripts/etc to migrate all the modules, that will be in it's favor, but really, I think there have got to be other things that are more worth doing than this.

If this was addressing some sort of real problem, or there really was a bikeshed about style
(but actually THIS thread is that bikeshed)

I think it's fine that different authors have their own style. someone's personal style won't stop me using or making a PR to that module. I've even made PRs to modules written in _coffeescript_.
Certainly, if the author of a module chose to use standard, if I made a PR to that module, I'd use standard too.

crypto-browserify (a module that I started) switched to standard - but by that point, new contributors had really picked up the project - but this isn't like that yet, it's still largely my work.

**Comment by dominictarr** [comment]
@ahdinosaur I've reconsidered this. If you really feel this is worth while, and want to write the scripts and migrate everything, then go ahead - I don't want to merge 50+ pull requests, but if you write a script that adds you as npm owner to those modules then I'll run it, and you can do it.

**Comment by ahdinosaur** [comment]
@dominictarr sweet. keen to be added as an npm owner, after i merged https://github.com/pull-stream/pull-stream/pull/54 i realized i couldn't actually publish a new version, so i reckon it'd be nice to have more org maintainers who can publish our modules, so we're not always dependent on you. will figure out how to make that setup easy for you.

regarding migrating all the modules to `standard`, i'm keen, but i'm not sure it's something that can be entirely automated (`standard-format` can only do so much, also not perfect conversion). how would you feel about an approach more like how i did https://github.com/pull-stream/pull-pushable/pull/5, basically whenever i touch a module to solve a tangible problem (or otherwise feel like touching a module), i'll also `standard` the code and add comments to explain what's happening, plus update the docs if i feel they are lacking. i feel this a better way to improve the org modules, but it does mean the migration journey will take longer.

**Comment by dominictarr** [comment]
I'd much rather see a concerted effort to update, at least the _important_ modules.
the whole point of consistent style is consistency,
so if you arn't gonna at least do a big push (how hard is it, anyway?) then it would be more consistent to note use standard.

**Comment by ahdinosaur** [comment]
> I'd much rather see a concerted effort to update, at least the important modules.

keen, that's what i had in mind but definitely did not communicate well, thanks.

**Comment by dominictarr** [comment]
Hey, so this has been 3 weeks since I said I'd accept this, if you were to do it all at once, or at least make a concerted effort.

So far you have made 3 pull requests (at this rate all of github.com/pull-stream will take 1 year)
and so far, when I see a diff it just kinda makes me mad -- the idea that some _computer program_ is gonna give me _errors_ because of _whitespace_. It's like coming into my house (of course, you are welcome anytime) and moving my toothbrush, socks, or the order of the knives and forks in the cutlery draw (not polite behavior for guests)

So, I'm sorry to say, I'm changing my mind on this again.
I'm not interested in merging any pull requests that change my code style.
I don't think it's important which code style you use, and "standardizing" any particular style isn't really a way forward. Accepting and respecting that other people have a particular way of doing things helps us grow as people. This is hard, but it's important to realize that our opinions are _just opinions_, having different code styles are good, because it gives us an opportunity to practice this.
A "standard" style kicks that challenge down the road but does not make it go away,
it'll still crop up in other ways.

See also isaac's now famous "pants" post https://groups.google.com/forum/#!msg/nodejs/MWaivVTirPY/0pnRjKsggkIJ

if you use standard in your own code (or any other style) or even any compile to js language,
that will not stop me from using it. If I make a pull request, I'll do it in your style.

I'm currently still pretty much the maintainer of all this code, but if this was rewritten by a team such that I could no longer fairly lay claim to having written all the code, then that team could choose whatever style they agreed to. (as I mentioned, this happened with crypto-browserify).

But, that is not the case with pull-stream, and i think it's unlikely to be the case,
since pull-stream is very simple and mostly pretty much done.

**Comment by ahdinosaur** [comment]
okay cool, i respect your house :boat: and more than happy to use your code style. :smile: i feel you on "Accepting and respecting that other people have a particular way of doing things helps us grow as people", i'll admit i have learned some unique JavaScript styles from reading your code. i have better contributions to offer than causing you to feel bad about your own awesome work, apologies for messing up a few rooms. :heart:

**Comment by dominictarr** [comment]
no problem. I've realized that I feel quite strongly about this. It had seemed that node community style customs had been settled a few years ago (your module, your style) but the popularity of standard seems to have brought a resurgence of style PRs.
