### ISSUE TITLE
Are pull-streams iterables?

### ISSUE THREAD

**Issue by brucou** [pull-stream/pull-stream#84]
This is not an issue and it will sound like a basic question, but I just got acquainted with pull-streams, and I was wondering how pull-streams were different from iterables/generator. A generator as you know is a function which returns an iterable from which you pull data. See the counterpart of `rxjs` called `ixjs` here : https://github.com/ReactiveX/IxJS

**Comment by jamen** [comment]
Hello @brucou!  I think the short answers is no.  They have a few differences which I think set them apart.  Disclaimer that I haven't actually used ReactiveX or IxJS, though.

 1. Pull streams are 1:1 with read and write.  In the pipeline everything feeds off a source stream and you don't generate more or less data the pipeline, you just operate off what the source gives you until it reaches a sink.  (this is the "pull" in pull-stream)  This is why things like `.reduce` don't exist as throughs in pull-stream.
 2. You don't need an explicit `Promise` object or a thing to handle and resolve them (in the case of [`co`](https://www.npmjs.com/package/co)-like systems).  Pull-streams are either async or sync.  Just cooked into how they are designed.
 3. I think parallelism with pull-streams is more elegant because of their functional and (sometimes) monoidic properties.  I could be wrong on this one though! (I'm kind of new to functional programming) I'm my opinion it's a lot more nice than a `AsyncIterator` class.

There is more differences on the topic of FP vs OOP, but that is a larger and you should research into it if you are interested!  There is some great talks online, even about the nitty-gritties of it.

However, I think the idea of a package for turning iterable into a source stream is cool!  (if that doesn't exist already?)   Perhaps ties a little bit in with #74

**Comment by dominictarr** [comment]
pull-streams are not iterators, but they are pretty close (and only depend on the simplest javascript features), it would be pretty easy to produce an adapter

**Comment by ahdinosaur** [comment]
> Pull streams are 1:1 with read and write.

hey @jamen, i might be misunderstanding you, but it's possible to have a through that reads 5 values and writes 1 value, or reads 5 value and writes 1, etc. for example, [`pull-through`](https://github.com/pull-stream/pull-through) makes this functionality easy, also [`pull-window`](https://github.com/pull-stream/pull-window).

**Comment by jamen** [comment]
@ahdinosaur Ah, I see.  I read the "1:1" piece somewhere from the docs might have been my misunderstanding.

**Comment by ahdinosaur** [comment]
@jamen oh yeah you're right: [here](https://github.com/pull-stream/pull-stream#11-read-callback-ratio).

**Comment by masaeedu** [comment]
@ahdinosaur Do you mean he's right about that being in the docs, or that it is impossible to implement `flatMap` or `reduce` combinators for pull-stream?

**Comment by ahdinosaur** [comment]
@masaeedu it's possible to implement those, see [`flatMap`](https://github.com/pull-stream/pull-flatmap/blob/master/index.js) or [`reduce`](https://github.com/pull-stream/pull-stream/blob/master/sinks/reduce.js) (this is as a sink, as a through is [`scan`](https://github.com/nichoth/pull-scan/blob/master/index.js)).
